### ISSUE TITLE
z.load("com.databricks:spark-csv_2.11:1.4.0")  fails probably because of proxy

### ISSUE THREAD

**Issue by nl19856** [hortonworks/data-tutorials#178]
Please Fill in the Following Information before submitting your Issue:

**Tutorial Name**:  Lab 102: Intro to Spark with Scala
**HDP Version are you Running**: 2.4
**Applicable HDP Components**:Zeppelin

**Link to tutorial**(Hortonworks or GitHub website): 
http://hortonworks.com/hadoop-tutorial/learning-spark-zeppelin/
### Detailed Description of Issue:

Execution of the first step in Lab102 fails on 
z.load("com.databricks:spark-csv_2.11:1.4.0") 
The error thrown in a java dump stack:
java.lang.NullPointerException  at ....
### Proposed Fix:

Adding a proxy somewhere in a configuration file???

**Comment by orendain** [comment]
Sorry for the delay!  That tutorial has been updated a few times since this issue was posted, and it looks to check out for the folks I know that ran through it.  Would you mind running through it again and seeing what you think?  Closing issue because of the recent updates, but feel free to reopen if an issue still exists with the tutorial.  Thanks!
