### ISSUE TITLE
docker image tar archive load fails with "no space left on device error" although there is free space

### ISSUE THREAD

**Issue by ksheytanov** [hortonworks/data-tutorials#181]
Please Fill in the Following Information before submitting your Issue:

**Tutorial Name**: Hortonworks Sandbox Guide  - (Docker)
**HDP Version are you Running**: 2.5
**Applicable HDP Components**: N/A

**Link to tutorial**(Hortonworks or GitHub website): http://hortonworks.com/hadoop-tutorial/hortonworks-sandbox-guide/#section_4
### Detailed Description of Issue:

Step 2 of the Sandbox deployment procedure instructs to load the image tar archive with the
docker load < <imagefilename.tar> command. ON a vanilla docker installation the docker load command will fail with an "no space left on device" error. This happens when the official docker installation instructions for CentOS 7 are followed (referenced with a link in the prerequisites section)

Steps to reproduce:
1. Install official CentOS 7 minimal.
2. Follow official instructions to install docker (involves adding the docker repo and installing with yum)
3. Follow the Docker Sandbox Guide.

The problem is that:
On CentOS (and the rest of the family) the docker daemon will default to using the devicemapper storage driver. This storage driver on its hand will default to using a Base Device Size of 10Gb while one of the layers in the sandbox image is ~14Gb. This layer doesn't fit in the default base device size thus the "no space left on device" error when loading the image. 

I was able to work my way around this by configuring the storage driver to use a size of 20Gb for the base image device(s) This is achieved by passing on the following daemon startup parameter:

--storage-opt dm.basesize=20G

After wiping /var/lib/docker (so the new setting can be taken into account when re-initializing) I was able to successfully deploy and start the sandbox, by following the rest of the guide.
### Proposed Fix:

Include instructions on how to configure the docker storage driver so it handles the sandbox correctly.

**Comment by orendain** [comment]
A bit late, but: this post is a great reference - it's helped at least one other use who stumbled here get back up and running.  Since HDP 2.6.x, we shouldn't run into this issue as layer sizes have been reduced.

The HDF sandbox was rearchitectured to more natively make use of Docker layers, and we're migrating HDP to our new build architecture to following suite.  In the meantime, the current version of HDP should also happen to be free from this issue.

I suggest we keep an eye on this, but I don't think new documentation is necessary considering the changes noted above (though I confess they would have if we had gotten to this issue sooner 😕)
