### ISSUE TITLE
Endless execution query time when using Drivers table

### ISSUE THREAD

**Issue by OrozcoJonathan** [hortonworks/data-tutorials#357]
**Tutorial name**: <Interactive Query for Hadoop with Apache Hive on Apache Tez>
**Platform version**: <HDP 2.6>
**Link to tutorial**: <https://hortonworks.com/tutorial/interactive-query-for-hadoop-with-apache-hive-on-apache-tez/>

### Description of issue:
When trying to run the queries that rely on both the drivers and timesheet table the query does not finish executing. It simply hangs and keeps the query as running even if it were stopped.

**Comment by gdeleon5** [comment]
BUG-84216 has been filed for Ambari/Hive resolution. Problem should be fixed in next release.

In the meantime, you may use:
**yarn application -list** to view current running  applications
then
**yarn application -kill** _<application_name>_ to kill old/outdated/not running applications

**NOTE:** Caution using this command - should only be used within sandbox environment.
