### ISSUE TITLE
Change org.openx.data.jsonserde.JsonSerDe to org.apache.hive.hcatalog.data.JsonSerDe

### ISSUE THREAD

**Issue by zz22394** [hortonworks/data-tutorials#399]
**Tutorial name**: Analyzing Social Media and Customer Sentiment With Apache NiFi and HDP Search
**Platform version**: HDP 2.6
**Link to tutorial**: 
https://github.com/hortonworks/data-tutorials/blob/master/tutorials/hdp/analyzing-social-media-and-customer-sentiment-with-apache-nifi-and-hdp-search/tutorial.md

### Description of issue:
Change ``org.openx.data.jsonserde.JsonSerDe`` to ``org.apache.hive.hcatalog.data.JsonSerDe`` can make the tutorial simpler.

As ``org.apache.hive.hcatalog.data.JsonSerDe`` is included in HDP 2.6, so I think we also don't need ``add jars``.

### Proposed fix (if any):
1) Change ``org.openx.data.jsonserde.JsonSerDe`` to ``org.apache.hive.hcatalog.data.JsonSerDe`` .
```
CREATE EXTERNAL TABLE IF NOT EXISTS tweets_text(
  tweet_id bigint,
  created_unixtime bigint,
  created_time string,
  lang string,
  displayname string,
  time_zone string,
  msg string)
ROW FORMAT SERDE 'org.apache.hive.hcatalog.data.JsonSerDe'
LOCATION '/tmp/tweets_staging';

```

2) Remove add jars/ maven building.

**Comment by james94** [comment]
This problem will be fixed very soon and I will share the link to the updated tutorial.

**Comment by james94** [comment]
@zz22394, parts of the "Analyzing Social Media and Customer Sentiment With Apache NiFi and HDP Search" tutorial have been integrated into "Building a Sentiment Analysis Application". This issue with json serde if using Hive is no longer an issue since we use Spark SQL to clean the data. It is the users option to use Hive if they want to, which is now outside the scope of this tutorial series.
