### ISSUE TITLE
Hive not starting on Windows Docker HDP 2.6 sandbox 

### ISSUE THREAD

**Issue by lalithakishore** [hortonworks/data-tutorials#402]
**Platform version**: <HDP 2.6, HDF 2.2, etc.>
OS: Windows 10
Docker Container Sandbox

Hive has not stared and tried to restart but realized "MySQL" is not starting and hence unable to start the Hiveserver properly.

Traceback (most recent call last):
 
2017-11-08 05:05:54,983 - checked_call[('/usr/lib/jvm/java/bin/java', '-cp', '/var/lib/ambari-agent/cred/lib/*', 'org.apache.ambari.server.credentialapi.CredentialUtil', 'get', 'javax.jdo.option.ConnectionPassword', '-provider', 'jceks://file/var/lib/ambari-agent/cred/conf/hive/hive-site.jceks')] {}
2017-11-08 05:05:55,794 - checked_call returned (0, 'SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".\nSLF4J: Defaulting to no-operation (NOP) logger implementation\nSLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.\nNov 08, 2017 5:05:55 AM org.apache.hadoop.util.NativeCodeLoader <clinit>\nWARNING: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable\nhadoop')
2017-11-08 05:05:55,802 - Execute[('service', 'mysqld', 'start')] {'logoutput': True, 'not_if': "pgrep -l '^mysqld$'", 'sudo': True}
MySQL Daemon failed to start.
Starting mysqld:  [FAILED]

Command failed after 1 tries:

**Comment by paul-lupu** [comment]
@lalithakishore  hello, we had some issues with the security settings for other platforms than RHEL based ones ( on ubuntu for example ). Could you please share the log for mysql? It should be in /var/log/mysql

**Comment by Castro38** [comment]
@lalithakishore, thank you for opening this issue. Please check out our latest HDP 2.6.4 and HDF 3.1 sandboxes at [](https://hortonworks.com/downloads/#sandbox). Let us know if your issue is still persisting with these new platforms.

**Comment by haivp3010** [comment]
I am running the latest HDP 2.6.5 on Docker on Pop! OS 17.10 (pretty much Ubuntu), but still mysqld failed to start.
Running `journalctl -xe` gives this log:

> 57144Z 0 [Warning] TIMESTAMP with implicit DEFAULT value is deprecated. Please use --explicit_defaults_for_timestamp server option (see documentation for more
58113Z 0 [Note] /usr/sbin/mysqld (mysqld 5.7.22) starting as process 7772 ...
60801Z 0 [Note] InnoDB: PUNCH HOLE support available
60823Z 0 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
60830Z 0 [Note] InnoDB: Uses event mutexes
60839Z 0 [Note] InnoDB: GCC builtin __atomic_thread_fence() is used for memory barrier
60845Z 0 [Note] InnoDB: Compressed tables use zlib 1.2.3
60851Z 0 [Note] InnoDB: Using Linux native AIO
61126Z 0 [Note] InnoDB: Number of pools: 1
61220Z 0 [Note] InnoDB: Using CPU crc32 instructions
62614Z 0 [Note] InnoDB: Initializing buffer pool, total size = 128M, instances = 1, chunk size = 128M
68395Z 0 [Note] InnoDB: Completed initialization of buffer pool
69690Z 0 [Note] InnoDB: If the mysqld execution user is authorized, page cleaner thread priority can be changed. See the man page of setpriority().
81130Z 0 [Note] InnoDB: Highest supported file format is Barracuda.
81214Z 0 [ERROR] InnoDB: **Operating system error number 13 in a file operation.**
81228Z 0 [ERROR] InnoDB: **The error means mysqld does not have the access rights to the directory.**
81236Z 0 [ERROR] InnoDB: Plugin initialization aborted with error Generic error
82004Z 0 [ERROR] Plugin 'InnoDB' init function returned error.
82072Z 0 [ERROR] Plugin 'InnoDB' registration as a STORAGE ENGINE failed.
82099Z 0 [ERROR] Failed to initialize builtin plugins.
82116Z 0 [ERROR] Aborting
 process exited, code=exited status=1
82202Z 0 [Note] Binlog end
qld failed: 0
82393Z 0 [Note] Shutting down plugin 'CSV'
83209Z 0 [Note] /usr/sbin/mysqld: Shutdown complete

I think the problem lies within the bold lines, but cannot work out how it could be fixed. The permission for /var/lib/mysql is mysql:mysql, which I guess is correct enough.

Could this problem be something related to the host not being RHEL based? (no SELinux, etc.)
I have also stopped mysql server from the host system, so that should probably not be a cause of the problem.

**Comment by paul-lupu** [comment]
@haivp3010 @vineshcpaul 

Hello, this is almost certainly to do with AppArmor if you're using a debian distro. You need to configure it to allow access or alternatively remove it completely if you have the liberty to do so.

**Comment by smdahmed** [comment]
For those reaching this link and running Ubuntu 20.04, please follow the instructions at: https://linuxconfig.org/how-to-disable-apparmor-on-ubuntu-20-04-focal-fossa-linux. There are specific instructions to disable apparmor for mysql.
