### ISSUE TITLE
maria_dev/raj_ops or any HDP user not working on putty for HDP azure

### ISSUE THREAD

**Issue by VParolkar** [hortonworks/data-tutorials#424]
**Tutorial name**: <Learning the Ropes of the Hortonworks Sandbox>
**Platform version**: <HDP 2.6, HDF 2.2, etc.>
**Link to tutorial**: <Either a Hortonworks link or GitHub link works fine>

### Description of issue:
I have an azure installation of HDP sandbox. When I use a normal azure created u
ser and password and conect via PUTTY ,I am able to connect. 

But when I use maria_dev or raj_ops or any HDP other user I am not able to connect to server via Putty.

**Comment by orendain** [comment]
@VParolkar When you connect via PuTTY, I assume you're connecting to the Azure VM itself.  The Hortonworks Sandbox runs in a container *within* the VM, so SSH'ing into the Azure VM isn't the same as SSH'ing into the sandbox.

[Here's documentation](https://hortonworks.com/tutorial/sandbox-deployment-and-install-guide/section/4/#configure-ssh-tunneling) on SSH'ing into the sandbox on Azure.  Feel free to report back if you run into any issues, we'll get you all set up! 😃

**Comment by VParolkar** [comment]
Hi Oreadain ,

I think I did not make it clear 
Thanks for your reply ,I am able to connect via putty ,but I am not able to use the default HDP users like maria_dev or raj_ops or any other default users.

Hope I clarified

Thanks
Vallabh

**Comment by orendain** [comment]
Hey @VParolkar, yeah I don't think I'm understanding correctly...

When you connect via PuTTY, what username do you use?  Are you using the username/password that you came up with when you set up the Azure VM?  Are you connecting via port 22?  If the answer to either question above is yes, then you are connecting to the Azure VM but *not* the sandbox inside of that VM.

The "real" sandbox is inside the Azure VM, so you can't PuTTY into the VM like you usually would.

Have you tried the [steps outlined here](https://hortonworks.com/tutorial/sandbox-deployment-and-install-guide/section/4/#configure-ssh-tunneling)?

**Comment by VParolkar** [comment]
Many thanks for your reply.

Under " Configuring ssh tunnelling " there are 2sections 

If I use "using Ssh" 
where should i 
vi ~/.ssh/config
After login in via putty using my azure vm id? 
because when i do so i dont get the config dir/file 

if I use "using putty"
and login via azure id after the setup
when will I used maria_dev as user?

Pls let me know
Thanks
v

**Comment by orendain** [comment]
Heya @VParolkar,

Since you're using PuTTY, you can skip the "Using SSH" section.  That section is for if you were using SSH on your local computer to connect to Azure.

Regarding the "Using PuTTY" section ... good question!

There are a few approaches - pick whichever you'd like (I'd recommend the first or second one)

1. After you connect to the Azure VM via PuTTY following that tutorial, open a browser to `http://<your-azure-vm-ip>:4200`  That should open up an SSH prompt for you to log straight into the sandbox with whatever user you'd like.
2. After connecting via PuTTY, log in with your Azure username/password.  Then, in the PuTTY terminal, SSH into the sandbox with whatever user you want ... `ssh -p 2222 maria_dev@sandbox-hdp.hortonworks.com`
3. After connecting via PuTTY as in the tutorial, open up a separate PuTTY window and connect to the Azure VM, but this time using the port "2222", using whichever sandbox user you'd like.

If that doesn't work, would you mind posting a few screenshots to see where in the process you are?  That way we can be more in sync.

Thanks!

**Comment by VParolkar** [comment]
thanks orendain ,now this is working

**Comment by orendain** [comment]
Hurray!  Feel free to report back if anything comes up - or post on https://community.hortonworks.com
