### ISSUE TITLE
Deploy Docker HDP Sandbox on VM VirtualBox Error 

### ISSUE THREAD

**Issue by saimach2002** [hortonworks/data-tutorials#497]
Tutorial name: Deploy Docker HDP Sandbox on Virtual Box
Platform version: Hortonworks Data Platform (HDP®) 2.6.4 on Hortonworks Sandbox - Docker
Link to tutorial: https://hortonworks.com/tutorial/sandbox-deployment-and-install-guide/section/1/ 

Description of issue:
OS: VirtualBox 5.2.10 Windows
following each step of the deployment guide:
downloaded file: start-sandbox-hdp-standalone_2-6-4.sh.zip
Import to : VirtualBox 5.2.10
then command: start
Issue:
in the script output , never get the final "Started Hortonworks HDP container" log.
instead, get:
waiting for ambari services to start
................................................................................
.................................................................................
................... etc ... which never ends.

**Comment by gdeleon5** [comment]
Hi @saimach2002 , 
Since you are using VirtualBox (Windows), the file you should be importing as an appliance is **HDP_2.6.4_virtualbox_01_02_2018_1428.ova**.  

You can get this file by [Download Page](https://hortonworks.com/downloads/#sandbox) -> "Hortonworks Data Platform (HDP®) 2.6.4 on Hortonworks Sandbox" -> DOWNLOAD FOR VIRTUALBOX

You should not be using **start-sandbox-hdp-standalone_2-6-4.sh** unless you are using native Docker on Linux/Mac.

Note: Make sure to allocate at least 8 GB (8192 MB) of RAM for the sandbox.
