### ISSUE TITLE
SMM is missing from the HDF 3.2 sandbox docker image

### ISSUE THREAD

**Issue by bluemonk3y** [hortonworks/data-tutorials#627]
**Tutorial name**: <Add tutorial name here>
**Platform version**: <HDP 2.6, HDF 3.2.8, etc.>
**Link to tutorial**: <Either a Hortonworks link or GitHub link works fine>

### Description of issue:
Logging into the Ambari interface I can add the metrics service - however the SMM service is missing

**Comment by LopezChris** [comment]
Hello,
HDF 3.2 is currently under development. This feature is currently being tested and it is intended for internal use only. Please stay tuned for the GA version of HDF 3.2 which will include SMM.

**Comment by LopezChris** [comment]
Hi,
Because the Sandbox is essentially a 1 Node cluster many configurations, which have been made to run on multi-node clusters, have to be changed and properly tested; for this reason, some features take longer to implement on the sandbox. We are expecting SMM to be available with the next GA version of the sandbox (HDF3.2). Please check back in during the next few weeks.
Thank you.
