### ISSUE TITLE
HDP Services do not show up when adding new service set in SAM

### ISSUE THREAD

**Issue by bdelamotte** [hortonworks/data-tutorials#633]
**Tutorial name**: Real-Time Event Processing In NiFi, SAM, Schema Registry and SuperSet
**Platform version**: Sandbox VM - VirtualBox version downloaded 9/4/2018
**Link to tutorial**: https://hortonworks.com/tutorial/real-time-event-processing-in-nifi-sam-schema-registry-and-superset/

### Description of issue:
When following the directions under "APPENDIX A: VISUALIZE TRUCKING DATA WITH SUPERSET VIA CDA", the guide tells you to create another service pool for HDP and click Auto Add. Then it tells you to create a new multi-node environment and select the services from the HDP service set. However, the services that the directions tell you to select do not get auto-added. Only KAFKA, STORM, AMBARI INFRA, and ZOOKEEPER show up, but the directions say to later select DRUID, HBASE, HDFS, HIVE. This appears to me that the auto-add feature is not picking up all of the services in the HDP cluster.

### Proposed fix (if any):
Fix the auto-add button to add the correct services or change the tutorial appropriately if there's an extra step needed to get those to show up.

**Comment by Castro38** [comment]
Hi @bdelamotte, thank you for sharing your issue with us. Likely the HDP services did not appear because the HDP Service Pool was not added. We have updated the tutorial to show the steps below for further clarification. 

Please try the following:

On Step 1: Configure SAM for CDA
1\. Open Stream Analytics Manager (SAM) at http://sandbox-hdf.hortonworks.com:7777/
2.Hover over the wrench to open the Configuration dropdown, select Service Pool, so we can add a new service pool for HDP.
3.In the field to the left of AUTO ADD, include the following:
http://sandbox-hdp.hortonworks.com:8080/api/v1/clusters/Sandbox
and then click AUTO ADD.

There will be a popup screen asking for username/password.
![screen shot 2018-09-05 at 5 28 45 pm](https://user-images.githubusercontent.com/34168140/45128136-34136400-b131-11e8-9db2-8cc8d9b7bce9.png)

**For user enter: admin
For the password you need enter the password you established when you reset the admin password. Learning the Ropes of the Hortonworks Sandbox:Admin Password Reset.**

When this is done successfully you will see the following image:
![screen shot 2018-09-05 at 5 29 45 pm](https://user-images.githubusercontent.com/34168140/45128154-4d1c1500-b131-11e8-8ef0-fe0d66319113.png)

You should now see services from the HDP Sandbox on the  SAM Service Pool Dashboard to the right of the HDF Sandbox Service Pool. We have now shared the web address of where SAM can find the services for the HDP Ambari Stack as seen on the image below:
![screen shot 2018-09-05 at 5 30 42 pm](https://user-images.githubusercontent.com/34168140/45128174-6fae2e00-b131-11e8-98a3-17f701836bcb.png)

Let me know if this helps.
