### ISSUE TITLE
Kafka port 6667 is not proxied in HDP 2.6.5 sandbox

### ISSUE THREAD

**Issue by pavel-sakun** [hortonworks/data-tutorials#782]
**Tutorial name**: Sandbox Port Forwarding Guide:Sandbox Port Forwarding on VirtualBox
**Platform version**: HDP 2.6.5 sandbox
**Link to tutorial**: https://hortonworks.com/tutorial/sandbox-port-forwarding-guide/section/1/

### Description of issue:
The issue is not documentation related, but issue with sandbox configuration. Issue was brought up in https://github.com/hortonworks/data-tutorials/issues/557#issuecomment-432131472 but validation performed by @gdeleon5 is not correct for the case as port 6667 specified in tcpPortsHDF so it doesn't get into conf.stream.d/tcp-hdp.conf as @rguillome mentioned, but it gets into proxy port forward rules as both tcpPortsHDF and tcpPortsHDP are merged together while generating proxy-deploy.sh.
Adding [6667]=6667 to tcpPortsHDP resolves issue with conf.stream.d/tcp-hdp.conf but this will cause proxy-deploy.sh fail because of 6667 port specified twice.

### Proposed fix (if any):
* use different port number for kafka in HDF image, update tcpPortsHDF and tcpPortsHDP appropriately (same approach as for zookeeper)
  or
* use either tcpPortsHDF or tcpPortsHDP while generating proxy-deploy.sh and update tcpPortsHDP with kafka port mapping

**Comment by gdeleon5** [comment]
@vineshcpaul,
Can you please take a look at this issue?

**Comment by vineshcpaul** [comment]
@pavel-sakun @rguillome @gdeleon5 
The easiest fix for this would be to edit the file /sandbox/deploy-scripts/generate-proxy-deploy-script.sh to get rid of the line '[6667]=6667' from array 'tcpPortsHDF' and add it to 'tcpPortsHDP'.
Then, re-generate proxy script and deploy proxy container by running the following commands:
sh assets/generate-proxy-deploy-script.sh
chmod ugo+x sandbox/proxy/proxy-deploy.sh
./sandbox/proxy/proxy-deploy.sh

Since this being a 2.6.5 sandbox, we do not have any plans to provide  a patch at this time.

**Comment by pavel-sakun** [comment]
@vineshcpaul while proposed workaround is not trivial to follow for someone not familiar with sandbox architecture(so please make sure that 3.x sandbox is not affected by this issue) it worked for me and now it got indexed, so could be found and followed.
